import { SessionProvider } from '@/utils/providers/SessionProvider';
import { readSessionAction } from '@/utils/session/crud/session-read-action';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { ReactNode } from 'react';
import './globals.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
	const session = await readSessionAction();

	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<SessionProvider initialSession={session}>{children}</SessionProvider>
			</body>
		</html>
	);
}
